version: 2
updates:
  # Using dependabot for all GHA violates pinning policy
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      # Check for new versions weekly
      interval: weekly
    # Update all actions in a single PR
    groups:
      github-actions:
        patterns: ["*"]
    labels:
      - automation
      - gha-update
    # Only allow updates for actions maintained by GitHub
    allow:
      - dependency-name: "actions/*"
      - dependency-name: "github-actions/*"

  # Automatically propose PRs for Go module dependencies
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      # Check for new versions weekly
      interval: weekly
    groups:
      go-updates:
        patterns: ["*"]
    labels:
      - automation
      - go-update
    commit-message:
      # Prefix all commit messages with "go: "
      prefix: "go"
