apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-api-janitor-openstack.fullname" . }}
  labels: {{ include "cluster-api-janitor-openstack.labels" . | nindent 4 }}
rules:
  # Required for kopf to watch resources properly
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - watch
  # Required for kopf to produce events properly
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
  # We need access to OpenStackClusters and the cloud credential secrets
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - delete
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - openstackclusters
    verbs:
      - list
      - get
      - watch
      - patch
